apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-products-deployment
spec:
  selector:
    matchLabels:
      app: api-products-pod
  template:
    metadata:
      labels:
        app: api-products-pod
    spec:
      containers:
        - name: api-products-container
          image: # valor será incluido no pipeline
          envFrom: # Use envFrom to load from ConfigMap and Secret
            - secretRef:
                name: api-products-secret
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
