name: Build ECR image and deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecr-${{ vars.PROJECT_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f src/infra.web-api/SnackTech.Driver.API/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      # Install Kubectl (generic installation method)j
      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure Kubectl
        run: |
          aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}
      
      - name: Replace connection string value
        env:
          MSSQL_CONNECTION_STRING: ${{ secrets.K8S_DB_CONNECTION_STRING }}
        run: |
          yq e '.data["msslq-connection-string"] = "'"$MSSQL_CONNECTION_STRING"'"' -i src/infra/eks/api/01-snack-tech-api-secret.yaml || { echo "Error updating msslq-connection-string value"; exit 1; }
      
      - name: Replace ECR image string value
        env:
          IMAGE_URI: ${{ steps.build-image.outputs.image }}
        run: |
          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i src/infra/eks/api/02-snack-tech-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
      - name: Deploy to EKS
        run: |
          kubectl apply -f src/infra/eks/api

  